title: AnythingLLM Environment Variables
id: 12345678-1234-5678-9abc-123456789042
status: experimental
description: Detects AnythingLLM environment variable configuration
author: AI Discovery Scanner
date: 2025-01-02
tags:
  - attack.discovery
  - attack.t1082
  - ai.llm
  - ai.anythingllm
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EnvironmentVariables|contains:
      - 'ANYTHING_LLM_'
      - 'ANYTHINGLLM_'
      - 'ANYTHING_LLM_TOKEN'
      - 'ANYTHING_LLM_HOST'
      - 'ANYTHING_LLM_MODEL'
  condition: selection
fields:
  - Image
  - CommandLine
  - EnvironmentVariables
  - User
falsepositives:
  - Legitimate AnythingLLM configuration
  - Development environment setup
level: low