title: Continue AI Environment Variables
id: 12345678-1234-5678-9abc-123456789018
status: experimental
description: Detects Continue AI environment variable configuration
author: AI Discovery Scanner
date: 2025-01-02
tags:
  - attack.discovery
  - attack.t1082
  - ai.llm
  - ai.continue
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EnvironmentVariables|contains:
      - 'CONTINUE_'
      - 'CONTINUE_AI'
      - 'CONTINUE_TOKEN'
      - 'CONTINUE_HOST'
      - 'CONTINUE_MODEL'
  condition: selection
fields:
  - Image
  - CommandLine
  - EnvironmentVariables
  - User
falsepositives:
  - Legitimate Continue AI configuration
  - Development environment setup
level: low