title: Jan AI Environment Variables
id: 12345678-1234-5678-9abc-123456789048
status: experimental
description: Detects Jan AI environment variable configuration
author: AI Discovery Scanner
date: 2025-01-02
tags:
  - attack.discovery
  - attack.t1082
  - ai.llm
  - ai.jan
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EnvironmentVariables|contains:
      - 'JAN_'
      - 'JAN_AI'
      - 'JAN_TOKEN'
      - 'JAN_HOST'
      - 'JAN_MODEL'
  condition: selection
fields:
  - Image
  - CommandLine
  - EnvironmentVariables
  - User
falsepositives:
  - Legitimate Jan AI configuration
  - Development environment setup
level: low