title: LocalAI Environment Variables
id: 12345678-1234-5678-9abc-123456789054
status: experimental
description: Detects LocalAI environment variable configuration
author: AI Discovery Scanner
date: 2025-01-02
tags:
  - attack.discovery
  - attack.t1082
  - ai.llm
  - ai.localai
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EnvironmentVariables|contains:
      - 'LOCALAI_'
      - 'LOCAL_AI_'
      - 'LOCALAI_TOKEN'
      - 'LOCALAI_HOST'
      - 'LOCALAI_MODEL'
  condition: selection
fields:
  - Image
  - CommandLine
  - EnvironmentVariables
  - User
falsepositives:
  - Legitimate LocalAI configuration
  - Development environment setup
level: low