title: Open WebUI Environment Variables
id: 12345678-1234-5678-9abc-123456789039
status: experimental
description: Detects Open WebUI environment variable configuration
author: AI Discovery Scanner
date: 2025-01-02
tags:
  - attack.discovery
  - attack.t1082
  - ai.llm
  - ai.openwebui
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EnvironmentVariables|contains:
      - 'OPEN_WEBUI_'
      - 'OPENWEBUI_'
      - 'WEBUI_'
      - 'OPEN_WEBUI_TOKEN'
      - 'OPEN_WEBUI_HOST'
      - 'OPEN_WEBUI_MODEL'
  condition: selection
fields:
  - Image
  - CommandLine
  - EnvironmentVariables
  - User
falsepositives:
  - Legitimate Open WebUI configuration
  - Development environment setup
level: low