title: Replit Ghostwriter Environment Variables
id: 12345678-1234-5678-9abc-123456789006
status: experimental
description: Detects Replit Ghostwriter environment variable configuration
author: AI Discovery Scanner
date: 2025-01-02
tags:
  - attack.discovery
  - attack.t1082
  - ai.llm
  - ai.ghostwriter
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EnvironmentVariables|contains:
      - 'GHOSTWRITER_'
      - 'REPLIT_GHOSTWRITER'
      - 'GHOSTWRITER_TOKEN'
      - 'GHOSTWRITER_HOST'
  condition: selection
fields:
  - Image
  - CommandLine
  - EnvironmentVariables
  - User
falsepositives:
  - Legitimate Replit Ghostwriter configuration
  - Development environment setup
level: low