title: Windsurf AI Environment Variables
id: 12345678-1234-5678-9abc-123456789009
status: experimental
description: Detects Windsurf AI environment variable configuration
author: AI Discovery Scanner
date: 2025-01-02
tags:
  - attack.discovery
  - attack.t1082
  - ai.llm
  - ai.windsurf
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EnvironmentVariables|contains:
      - 'WINDSURF_'
      - 'WINDSURF_AI'
      - 'WINDSURF_TOKEN'
      - 'WINDSURF_HOST'
  condition: selection
fields:
  - Image
  - CommandLine
  - EnvironmentVariables
  - User
falsepositives:
  - Legitimate Windsurf AI configuration
  - Development environment setup
level: low